### ISSUE TITLE
Existing packages

### ISSUE THREAD

**Issue by thosakwe** [getdbjs/dartspatcher#1]
Hi, nice work on the package! I'd also like to let you know that I have written a package that performs routing, with support for many advanced features, including route groups.

It's called `angel_route`, and I hope that you consider contributing: https://github.com/angel-dart/route

I also have a package you can use to parse request bodies: https://github.com/thosakwe/body_parser

And lastly, to get the query parameters from an `HttpRequest`, all you have to do is get `request.uri.queryParameters`, rather than manually parsing them.

My goal here is just to reduce the amount of duplicate packages. Thank you for your contributions to the Dart community!!!

**Comment by getdbjs** [comment]
Hi, thank you for your comment. this is my experiment but it isn't a problem because there are many packages that often to do similar things in this and other tecnologies.
